import type { Metadata } from "next";
import { Geist, Geist_Mono,AR_One_Sans,Alatsi } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const ziti=Alatsi({subsets: ["latin"],weight:'400'})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={ziti.className}
      >
        {children}
      </body>
    </html>
  );
}
